---
title: "Milestone-2"
author: "Aysha Emmerson"
date: "19/09/2019"
output: html_document
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)

#Project Pros and Cons (1)

#caievelyn's outwit_outplay_outlast 

#Evelyn Cai’s outwit_outplay_outlast project analyzes data collected from 37 seasons of CBS’s Survivor, displaying this data using “ShinyApp.” The consistent structure of the show as well as the many seasons it has to explore data from, makes Survivor a great choice of series for this project. On ShinyApp, Evelyn does a good job of displaying her data using a diversity of formats. The “Explore the Dataset” interface is particularly cool, as it provides users with the opportunity to personally engage with the aspects of the data that they find most interesting. In this section, Evelyn does a good job at narrowing in on the most important variables. After clicking “display,” the data is presented in an exceedingly readable, straightforward way, making it accessible to anyone. Furthermore, in each of her “Outwit,” “Outplay,” “Outlast” sections, Evelyn does a good job at providing context for the variables she’s working with as well as provides a brief analysis of what her results might indicate. This being said, it would have been interesting to have seen her take this analysis a little further in some places. In addition, while the project is overall impressive in its content, the user interface is not particularly visually appealing. A range of font types and font sizes are used in an inconsistent way, which is at times distracting. Furthermore, the white “chunks” of background, which appear to be pasted onto a golden/brown colored image, is also fairly unaesthetic and could be improved.
```
```{r}

#Project Pros and Cons (2)

#wsmiles000’s Trumps-Tweets-Stock-Market

#Wsmiles000’s project uses an interactive RShiny application to allow users to compare President Trump’s tweets with “intraday stock pricing and trade volume fluctuations.” The project’s data comes from Twitter API and the QuantTools library. Not only does Wsmiles000’s project use the RShiny application to share information with users, but users can also run a script in their own console that updates the tweet data as well as can run the application locally through the RStudio desktop client. These features of the project are particularly impressive, providing users the multiple ways to engage with the dataset. The ShinyApp interface is simple but consistent in its visual appeal. The white background allows for reader’s attention to remain focused on the data and data visualizations. Furthermore, the “About” page is helpful in explaining how to use the other pages. One area where the project could be improved, is it would have been interesting for Wsmiles000 to provide some greater analysis/explanation of their findings. Why is the relationship between Trump’s tweets and the stock market significant? Did any trends arise when they were making these comparisons? In addition, it could have been interesting to see their data visualized using a greater variety of formats.
```

